# Generated by Django 5.2.3 on 2025-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.AddField(
            model_name='news',
            name='required_login',
            field=models.BooleanField(default=False, help_text='If true, only authenticated users can view this news item'),
        ),
    ]
