# Generated by Django 5.2.3 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_view_count_news_required_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_ru',
            field=models.SlugField(max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_uz',
            field=models.SlugField(max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
