# Generated by Django 5.2.3 on 2025-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_category_slug_en_remove_category_slug_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='If set, news will be published at this time', null=True),
        ),
    ]
